int _puthchar(char c);
int _isupper(int c);
int _isdigit(int c);
int mul(int a,int c);
void print_number(void);
void print_most_numbers(void);
void more_numbers(void);
void print_line(int n);
void print_daigonal(int n);
void print_squre(int size);
void print_traingle(int size);
void print_number(int n);
